### ISSUE TITLE
Game crashes when executing a lord

### ISSUE THREAD

**Issue by rasheedja** [tynakuh/TyniBannerlordFixes#3]
I've encountered a bug where my game crashes when executing a lord of a minor faction. I narrowed down the cause of the crash to this mod being active. The crash occurs on both 1.3.0 and 1.4.0

## Reproduction
To reproduce, execute a minor lord you've captured.

Here's my save file where I have a captured lord in my party. The game will crash if you execute the lord while having this module active.

[save_014.zip](https://github.com/tynakuh/TyniBannerlordFixes/files/4447314/save_014.zip)

I don't know if the game would crash if executing a lord of a major faction.

## Workaround
1. Deactivate this module
2. Execute lord and save
3. Reactivate module

Let me know if you need any more info

**Comment by tynakuh** [comment]
Thanks for the detailed bug report! Thats interesting,, I'll take a look

**Comment by tynakuh** [comment]
1.4.1 should fix this.
